---
# defaults file for elasticsearch
es_java_install: true
update_java: false
es_major_version: "7.x"
es_version: "7.1.1"
es_use_repository: true
es_package_name: "elasticsearch-oss"
es_restart_on_change: true
es_start_service: true
es_group: "elasticsearch"
conf_dir: "/etc/elasticsearch"
es_api_port: 9200
es_api_host: "localhost"

es_nodes: |-
        {% for item in groups['es-cluster'] -%}
          {{ hostvars[item]['ip'] }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

populate_inventory_to_hosts_file: true

es_plugin_bin_path: /usr/share/elasticsearch/bin/elasticsearch-plugin install
es_sec_plugin_conf_path: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
es_sec_plugin_tools_path: /usr/share/elasticsearch/plugins/opendistro_security/tools
